// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackageMicroservice.Core.API.Models;

#nullable disable

namespace PackageMicroservice.Core.API.Migrations
{
    [DbContext(typeof(PackageDbContext))]
    [Migration("20241203094239_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PackageMicroservice.Core.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Adventure"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nature"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Religious"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Village"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Wildlife"
                        });
                });

            modelBuilder.Entity("PackageMicroservice.Core.API.Models.Package", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PackageId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            PackageId = 1,
                            CategoryId = 1,
                            Description = "Experience thrilling treks in the Himalayan region.",
                            PackageName = "Himalayan Trek"
                        },
                        new
                        {
                            PackageId = 2,
                            CategoryId = 2,
                            Description = "Relax on the serene beaches of Goa.",
                            PackageName = "Goa Beach Bliss"
                        },
                        new
                        {
                            PackageId = 3,
                            CategoryId = 3,
                            Description = "Discover the spiritual aura of Varanasi.",
                            PackageName = "Spiritual Varanasi"
                        },
                        new
                        {
                            PackageId = 4,
                            CategoryId = 4,
                            Description = "Explore the vibrant rural culture of Rajasthan.",
                            PackageName = "Rural Rajasthan"
                        },
                        new
                        {
                            PackageId = 5,
                            CategoryId = 5,
                            Description = "Witness the majestic one-horned rhinos in their natural habitat.",
                            PackageName = "Kaziranga Safari"
                        },
                        new
                        {
                            PackageId = 6,
                            CategoryId = 1,
                            Description = "Explore the snow-capped mountains of the Swiss Alps.",
                            PackageName = "Swiss Alps Adventure"
                        },
                        new
                        {
                            PackageId = 7,
                            CategoryId = 2,
                            Description = "Unwind in the tropical beauty of Maldives.",
                            PackageName = "Maldives Paradise"
                        },
                        new
                        {
                            PackageId = 8,
                            CategoryId = 3,
                            Description = "Walk through the sacred landmarks of Jerusalem.",
                            PackageName = "Holy Jerusalem"
                        },
                        new
                        {
                            PackageId = 9,
                            CategoryId = 4,
                            Description = "Immerse yourself in the tranquil Japanese villages.",
                            PackageName = "Japanese Countryside"
                        },
                        new
                        {
                            PackageId = 10,
                            CategoryId = 5,
                            Description = "Discover the incredible biodiversity of the Amazon.",
                            PackageName = "Amazon Rainforest"
                        });
                });

            modelBuilder.Entity("PackageMicroservice.Core.API.Models.PackageImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageImage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "images/himalayan_trek.jpg",
                            PackageId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "images/himalayan_trek1.jpg",
                            PackageId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "images/himalayan_trek2.jpg",
                            PackageId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "images/himalayan_trek3.jpg",
                            PackageId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "images/goa_beach.jpg",
                            PackageId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "images/goa_beach1.jpg",
                            PackageId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "images/goa_beach2.jpg",
                            PackageId = 2
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "images/varanasi.jpg",
                            PackageId = 3
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "images/varanasi1.jpg",
                            PackageId = 3
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "images/varanasi2.jpg",
                            PackageId = 3
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "images/rural_rajasthan.jpg",
                            PackageId = 4
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "images/rural_rajasthan1.jpg",
                            PackageId = 4
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "images/rural_rajasthan2.jpg",
                            PackageId = 4
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "images/kaziranga_safari.jpg",
                            PackageId = 5
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "images/kaziranga_safari1.jpg",
                            PackageId = 5
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "images/kaziranga_safari2.jpg",
                            PackageId = 5
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "images/swiss_alps.jpg",
                            PackageId = 6
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "images/swiss_alps1.jpg",
                            PackageId = 6
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "images/swiss_alps2.jpg",
                            PackageId = 6
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "images/maldives.jpg",
                            PackageId = 7
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "images/jerusalem.jpg",
                            PackageId = 8
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "images/japanese_countryside.jpg",
                            PackageId = 9
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "images/amazon.jpg",
                            PackageId = 10
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "images/maldives1.jpg",
                            PackageId = 7
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "images/maldives2.jpg",
                            PackageId = 7
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "images/jerusalem1.jpg",
                            PackageId = 8
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "images/jerusalem2.jpg",
                            PackageId = 8
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "images/japanese_countryside1.jpg",
                            PackageId = 9
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "images/japanese_countryside2.jpg",
                            PackageId = 9
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "images/amazon1.jpg",
                            PackageId = 10
                        },
                        new
                        {
                            Id = 31,
                            ImageUrl = "images/amazon2.jpg",
                            PackageId = 10
                        });
                });

            modelBuilder.Entity("PackageMicroservice.Core.API.Models.SubPackage", b =>
                {
                    b.Property<int>("SubPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubPackageId"));

                    b.Property<string>("DaysNights")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("PlaceToVisit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerAdult")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SubPackageId");

                    b.HasIndex("PackageId");

                    b.ToTable("SubPackages");

                    b.HasData(
                        new
                        {
                            SubPackageId = 1,
                            DaysNights = "5 Days / 4 Nights",
                            Description = "A serene valley with stunning views.",
                            PackageId = 1,
                            PlaceToVisit = "Manali",
                            PricePerAdult = 1200.00m
                        },
                        new
                        {
                            SubPackageId = 2,
                            DaysNights = "3 Days / 2 Nights",
                            Description = "A high-altitude pass with breathtaking vistas.",
                            PackageId = 1,
                            PlaceToVisit = "Rohtang Pass",
                            PricePerAdult = 1000.00m
                        },
                        new
                        {
                            SubPackageId = 3,
                            DaysNights = "4 Days / 3 Nights",
                            Description = "A bustling beach with vibrant nightlife.",
                            PackageId = 2,
                            PlaceToVisit = "Calangute Beach",
                            PricePerAdult = 800.00m
                        },
                        new
                        {
                            SubPackageId = 4,
                            DaysNights = "2 Days / 1 Night",
                            Description = "Spectacular waterfalls surrounded by lush greenery.",
                            PackageId = 2,
                            PlaceToVisit = "Dudhsagar Falls",
                            PricePerAdult = 700.00m
                        },
                        new
                        {
                            SubPackageId = 5,
                            DaysNights = "3 Days / 2 Nights",
                            Description = "A sacred temple dedicated to Lord Shiva.",
                            PackageId = 3,
                            PlaceToVisit = "Kashi Vishwanath Temple",
                            PricePerAdult = 500.00m
                        },
                        new
                        {
                            SubPackageId = 6,
                            DaysNights = "2 Days / 1 Night",
                            Description = "Experience the spiritual Ganga Aarti.",
                            PackageId = 3,
                            PlaceToVisit = "Ganga Ghats",
                            PricePerAdult = 400.00m
                        },
                        new
                        {
                            SubPackageId = 7,
                            DaysNights = "3 Days / 2 Nights",
                            Description = "Explore the famous Pushkar Camel Fair.",
                            PackageId = 4,
                            PlaceToVisit = "Pushkar",
                            PricePerAdult = 1000.00m
                        },
                        new
                        {
                            SubPackageId = 8,
                            DaysNights = "4 Days / 3 Nights",
                            Description = "Experience traditional Rajasthani hospitality.",
                            PackageId = 4,
                            PlaceToVisit = "Jodhpur Villages",
                            PricePerAdult = 1200.00m
                        },
                        new
                        {
                            SubPackageId = 9,
                            DaysNights = "5 Days / 4 Nights",
                            Description = "A UNESCO World Heritage site.",
                            PackageId = 5,
                            PlaceToVisit = "Kaziranga National Park",
                            PricePerAdult = 2000.00m
                        },
                        new
                        {
                            SubPackageId = 10,
                            DaysNights = "4 Days / 3 Nights",
                            Description = "A picturesque town surrounded by mountains.",
                            PackageId = 6,
                            PlaceToVisit = "Interlaken",
                            PricePerAdult = 3000.00m
                        },
                        new
                        {
                            SubPackageId = 11,
                            DaysNights = "5 Days / 4 Nights",
                            Description = "Home to the iconic Matterhorn peak.",
                            PackageId = 6,
                            PlaceToVisit = "Zermatt",
                            PricePerAdult = 3500.00m
                        },
                        new
                        {
                            SubPackageId = 12,
                            DaysNights = "3 Days / 2 Nights",
                            Description = "Explore the capital city of Maldives.",
                            PackageId = 7,
                            PlaceToVisit = "Male City",
                            PricePerAdult = 2500.00m
                        },
                        new
                        {
                            SubPackageId = 13,
                            DaysNights = "4 Days / 3 Nights",
                            Description = "Relax in luxurious overwater villas.",
                            PackageId = 7,
                            PlaceToVisit = "Resort Islands",
                            PricePerAdult = 4000.00m
                        },
                        new
                        {
                            SubPackageId = 14,
                            DaysNights = "4 Days / 3 Nights",
                            Description = "Walk through the historic landmarks.",
                            PackageId = 8,
                            PlaceToVisit = "Old City",
                            PricePerAdult = 1800.00m
                        },
                        new
                        {
                            SubPackageId = 15,
                            DaysNights = "3 Days / 2 Nights",
                            Description = "A traditional Japanese village with iconic houses.",
                            PackageId = 9,
                            PlaceToVisit = "Shirakawa-go",
                            PricePerAdult = 2200.00m
                        },
                        new
                        {
                            SubPackageId = 16,
                            DaysNights = "4 Days / 3 Nights",
                            Description = "Known for hot springs and Mount Fuji views.",
                            PackageId = 9,
                            PlaceToVisit = "Hakone",
                            PricePerAdult = 2400.00m
                        },
                        new
                        {
                            SubPackageId = 17,
                            DaysNights = "5 Days / 4 Nights",
                            Description = "Gateway to the Amazon jungle.",
                            PackageId = 10,
                            PlaceToVisit = "Manaus",
                            PricePerAdult = 2700.00m
                        },
                        new
                        {
                            SubPackageId = 18,
                            DaysNights = "6 Days / 5 Nights",
                            Description = "Discover the diverse wildlife of the Amazon.",
                            PackageId = 10,
                            PlaceToVisit = "Amazon River Cruise",
                            PricePerAdult = 3000.00m
                        });
                });

            modelBuilder.Entity("PackageMicroservice.Core.API.Models.Package", b =>
                {
                    b.HasOne("PackageMicroservice.Core.API.Models.Category", "Category")
                        .WithMany("Packages")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PackageMicroservice.Core.API.Models.PackageImage", b =>
                {
                    b.HasOne("PackageMicroservice.Core.API.Models.Package", "Package")
                        .WithMany("Images")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PackageMicroservice.Core.API.Models.SubPackage", b =>
                {
                    b.HasOne("PackageMicroservice.Core.API.Models.Package", "Package")
                        .WithMany("SubPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("PackageMicroservice.Core.API.Models.Category", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("PackageMicroservice.Core.API.Models.Package", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("SubPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
